
server:
  port: 80

#链路追踪
spring:
  zipkin:
    base-url: http://192.168.200.100:9411/
    sender:
      type: web

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" #允许所有地址来源跨域
            allowedMethods: "*" #允许所有请求方式跨域
            allowedHeaders: "*" #复杂跨域的原因就是因为带来一些复杂的请求头导致，
            allowCredentials: true #允许带一些安全标致跨域 比如：Cookie
      #所有网关路由规则
      routes:
        - id: product_route
          uri: lb://service-product
          predicates:  #断言
            - Path=/admin/product/**

        - id: user_route
          uri: lb://service-user
          predicates:
           - Path=/api/user/**

        - id: web_all_route
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com

