
server:
  port: 80

#链路追踪
spring:
  zipkin:
    base-url: http://192.168.200.100:9411/
    sender:
      type: web

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" #允许所有地址来源跨域
            allowedMethods: "*" #允许所有请求方式跨域
            allowedHeaders: "*" #复杂跨域的原因就是因为带来一些复杂的请求头导致，
            allowCredentials: true #允许带一些安全标致跨域 比如：Cookie
      #所有网关路由规则
      routes:
        - id: product_route
          uri: lb://service-product
          predicates:  #断言
            - Path=/admin/product/**

        - id: incr_route
          uri: lb://service-item
          predicates:
            - Path=/lock/incr

        - id: user_route
          uri: lb://service-user
          predicates:
            - Path=/api/user/**

        - id: cart_router
          uri: lb://service-cart
          predicates:
            - Path=/api/cart/**

        - id: order_router
          uri: lb://service-order
          predicates:
            - Path=/api/order/**


        - id: web_all_route
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com

app:
  auth:
    no-auth-url:  #任意人无需登录都能访问的路径
      - /css/**
      - /js/**
      - /img/**
      - /login.html
      - /api/user/passport/login

    login-auth-url: #登录以后才能访问的资源
      - /order/**
      - /trade.html
    deny-url:
      - /api/inner/**

    login-page: http://passport.gmall.com/login.html

